runtime: php55
api_version: 1

handlers:
- url: /
  script: index.php

- url: /index\.html
  script: index.php
  
- url: /exports
  script: exports.php
  
- url: /data.json
  script: graphs.php

- url: /static
  static_dir: static