runtime: php55
api_version: 1

handlers:
- url: /
  script: index.php
  secure: always

- url: /index\.html
  script: index.php
  secure: always
  
- url: /exports
  script: exports.php
  secure: always
  
- url: /exports/download\..+
  script: exportsdownload.php
  secure: always
  
- url: /data.json
  script: graphs.php
  secure: always
  
- url: /cron/(.+)
  script: cronjobs/\1.php
  login: admin

- url: /static
  static_dir: static
  secure: always